[db]
data-source = "postgresql://eartinity:va4RWm5X6bYqQJApbLeqiIGMIqGHkgdE@dpg-d55betfgi27c73ehhuk0-a.oregon-postgres.render.com/eartinity_teldrive"
prepare-stmt = false

[db.pool]
enable = false

[jwt]
allowed-users = ["Eartinity_AFK"]
secret = "Hellothere@29"

[tg.uploads]
encryption-key = "Hellothere@29"
